server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Cấu hình chặn lỗi 404 cho React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bỏ cache file HTML để luôn cập nhật giao diện mới nhất
    location ~* \.(?:html)$ {
        expires -1;
    }
}