worker_processes auto;

events {
    worker_connections 1024;
}

# Sử dụng 'stream' cho Tầng 4 (TCP) thay vì 'http'
stream {
    upstream postgres_read_cluster {
        server bds-db-master:5432;
        server bds-db-replica:5432;
    }

    server {
        listen 5433;
        proxy_pass postgres_read_cluster;
        proxy_connect_timeout 5s;
    }
}